### ISSUE TITLE
Speeding up BLAST (Phasing out GI numbers)

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#113]
So in order to keep our code-base up to date, we need to drop the GI list functionality.
[link](https://ncbiinsights.ncbi.nlm.nih.gov/2016/07/15/ncbi-is-phasing-out-sequence-gis-heres-what-you-need-to-know/)

I think it would be best for long term development if we do this.  It would simply require changing the following:     
 * _-outfmt '%g %T'_ **to** _-outfmt '%a %T'_ (blastdbcmd)
*  gilist parameter to seqidlist parameter (NCBIblastnCommandline)

So instead of creating GI list we are creating Accession.Version lists.

To my understanding this should be a relatively seamless transition.
Alternatively we can also create a masked database, but I know you have more experience with that than I do @sdhutchins

**Comment by sdhutchins** [comment]
@grabear Completely agree here with this. I'm going to take it down to Medium Priority because it's important but not hindering the completeness of the package working (gi vs accession). I'll address that as I continue to rework the gi_list_config function and keep you updated on where I get with that.

**Comment by sdhutchins** [comment]
Will work to phase in https://www.ncbi.nlm.nih.gov/books/NBK279668/#_usermanual_BLASTWindowMasker_integration_

**Comment by grabear** [comment]
#115 has been issued to document deprecation of GI numbers.

**Comment by sdhutchins** [comment]
#120
