### ISSUE TITLE
Index File Consistency

### ISSUE THREAD

**Issue by grabear** [datasnakes/Datasnakes-Scripts#2]
# Minimization
Right now we have a ton of different files we are using as an index for our project.  I'd like to propose that we narrow it down to a minimum.  Currently we have the following:
1. MAFV3.1.csv
2. MAFV3.2.csv
3. MAFV3.3.csv
4. Homo_sapiens_Accession.csv
5. Macaca_mulatta_Accession.csv
6. Organisms & Taxonomy IDs.csv
7. Organisms.csv
8. taxids.csv
9. ShinyGenes.csv
10. ShinyOrganisms.csv
11. shinydir_mana.txt
12. commonnames.csv

- [x] The first 3 are test files for the Analysis class so they will eventually go.
- [x] We can get rid of _4_, _5_, and _6_ because they are redundant.
- [ ] We can keep _8_ for now, but I'd like to work the taxon id's into our Master Accession file (it will be easier to keep them ordered this way) for offline use, and get them from ete3 for online use.
- [x] For _9_ and _10_ we were using these because of weird compatibility with R and Python, but I know there is a much better way to deal with this via csv file/dataframe.   So we can get rid of these two files, but only after we fix the shiny app code that deals with these files.
- [ ] _11_ is a configuration file for the shiny app so we can do something different with this...
- [x] And lastly _12_.  This file is useful but we can do it programmatically as well, so this also seems redundant.
- [ ] I'd also like to keep the GI files here.
**Note:**  _This is just from my perspective so if you need any one of these files just say so.  I just wanted to narrow down on what we have and standardize the naming conventions._
# Standardization
In order to standardize things we need to come up with a naming convention.  I propose that we use extensions to identify file types:

- [x] For accession files we denote them with a _*.ma*_.  The user (for now just us) can name them **ANYTHING**!!  So it could be _Crazy-MAST-ACC.ma.csv_
- [x] For taxids it could be _*.tax*_.
- [x] Our database files (BLAST and RefSeq) will be different.  We can access them via directory name.

**Comment by sdhutchins** [comment]
We don't need the commonnames.csv file with ETE3. Human/Rhesus accessions files are there because they were originally there (mainly for GPCR dataset). It's a file that I now create from the main accession file, but not necessary. The only important file is organisms + tax ids. How we generate the final master accession file is unimportant to me in terms of whether it has taxonomy ids or not. As long as the species name is there, we're good. I haven't actually used files 9 or 10 with shiny. I've just used any files we've produced via the pipeline.

I have no issue with any of the naming formats.

**Comment by grabear** [comment]
Ok, good deal so you only need the organisms file and tax ids file.  When are they used?

Right now the Analysis class takes a csv file in the standard format we've been using:
Header:  _Tier, Gene, Org1....Orgn_

In the future I'm thinking about changing our indexing information as follows:

The user will be able to pick one of the following styles:

1.  Give a Master Accession file with all the info we need in one _.xlxs_ file
    - Gene Worksheet (Tier, Entrez ID, Gene)
    - Organism Worksheet (Taxid, Organism, Kingdom, Phylum, Class, Order, Family, Genus, Species)
        - We can get the taxonomic rank via ete3 as well, so we will only need the header.

**_OR_**    
    
2.  Give a separate Gene _.csv_ file and seperate Organism _.csv_ file with same info as the excel worksheets above.

**Comment by sdhutchins** [comment]
Yeah, wherever those files are created or used will just have to be changed. The organisms and taxids are used for blastn and created in the blast setup (organisms file is just standard to organisms we use). I haven't looked at what you've changed yet, but I can. I'd prefer not to work with an .xls file (harder to manipulate and visualize on github and with other software - most programs prefer text-based like the .csv format or .txt format), but I can.  Also, I'm thinking of changing the Entrez ID to an Ensembl ID. We can certainly provide the deeper taxonomy information. That's not a hard thing to get. Also, maybe instead of tier, we could use **Gene Ontology Association** or something similar. (I was just reading a paper that used that.) I'm not tied to any of it.

**Comment by sdhutchins** [comment]
Hey I only locked this so people who have starred it won't be being nosy lol @grabear that way only contributors can discuss
